Bayer-Group/ol-kit

- package-lock.json
- package.json
- src/Basemaps/__snapshots__/BasemapManager.test.js.snap
- src/Basemaps/__snapshots__/BingMaps.test.js.snap
- src/Basemaps/__snapshots__/BlankWhite.test.js.snap
- src/Basemaps/__snapshots__/OpenStreetMap.test.js.snap
- src/Basemaps/__snapshots__/StamenTerrain.test.js.snap
- src/Basemaps/__snapshots__/StamenTonerDark.test.js.snap
- src/Basemaps/__snapshots__/StamenTonerLite.test.js.snap
- src/Map/Map.js
- src/Map/Map.test.js
due to the movement of `createMap` into the constructor, the map mounted to the div before it mounted to the page and never rendered, successfully returning a reference to the `map` but leaving the screen white
> Hotfix map render

- docs/Basemaps_BingMaps.js.html
- docs/Basemaps_BlankWhite.js.html
- docs/Basemaps_OpenStreetMap.js.html
- docs/Basemaps_StamenTerrain.js.html
- docs/Basemaps_StamenTonerDark.js.html
- docs/Basemaps_StamenTonerLite.js.html
- docs/CNAME
- docs/Controls_ZoomControls.js.html
- docs/Map_Map.js.html
- package-lock.json
- package.json
- src-docs/overrides/CNAME
- src/Basemaps/BlankWhite.js
- src/Basemaps/OpenStreetMap.js
- src/Basemaps/StamenTerrain.js
- src/Basemaps/StamenTonerDark.js
- src/Basemaps/StamenTonerLite.js
- src/Controls/ZoomControls.js
This fixes the missing CNAME for GH pages & fixes all lint errors
> Fixed missing CNAME record

- MAINTAINERS.md
- docs/index.html
- docs/tutorial-Getting Started.html
- package-lock.json
- package.json
- src-docs/overrides/index.html
- src-docs/tutorials/Getting Started.md
> Doc updates

- .gitattributes
See docs for Linguist on what this is doing: https://github.com/github/linguist#using-gitattributes
> Added a .gitattributes file to help GH linguist understand the project

- .github/workflows/integrate.yml
> Feature: Added GH Action to Lint and Test PRs

- package-lock.json
- package.json
> adding missing dependency of lodash.isequal

- README.md
- docs/PopupActionGroup.html
- docs/PopupActionItem.html
- docs/PopupDataList.html
- docs/PopupDefaultPage.html
- docs/PopupPageLayout.html
- docs/PopupPageLayoutChild.html
- docs/PopupTabs.html
- docs/index.html
- docs/tutorial-Getting Started.html
- src-docs/overrides/index.html
- src-docs/tutorials/Getting Started.md
> document material ui peerDependencies

- docs/LayerStyler_LayerStyler.js.html
- docs/PopupActionGroup.html
- docs/PopupActionItem.html
- docs/PopupDataList.html
- docs/PopupDefaultPage.html
- docs/PopupPageLayout.html
- docs/PopupPageLayoutChild.html
- docs/PopupTabs.html
- package-lock.json
- package.json
- src/LayerStyler/LayerStyler.js
- src/locales/en.js
> patch to get valid layers for layer styler

- docs/CNAME
> add CNAME file back for docs site

- package-lock.json
- package.json
- src/LayerPanel/LayerPanelActionOpacity/styled.js
- src/LayerPanel/LayerPanelLayersPage/index.js
Resolves: [issue-113](https://github.com/MonsantoCo/ol-kit/issues/113)
> layerpanel expand issue and layerpanel opacity width

- package-lock.json
- package.json
- src/Popup/Popup.js
- src/Popup/utils.js
- src/Popup/utils.test.js
> add support for clustered features clicks

- src/Popup/PopupInsert/PopupDefaultInsert.js
> add safeSelectedIdx check to prevent popup bug

- package-lock.json
- package.json
- src/LayerPanel/LayerPanelList/index.js
Resolves: https://github.com/MonsantoCo/ol-kit/issues/138
> Replace react-smooth-dnd

- .github/workflows/deploy-to-s3.yml
- src/GooglePlacesSearch/GooglePlacesSearch.js
> github workflow was pointing to the wrong build folder

- src/GooglePlacesSearch/GooglePlacesSearch.js
- src/Popup/Popup.js
- src/Popup/Popup.test.js
> Now popup wont show when double to zoom over feature

- package-lock.json
- package.json
> bump to 0.16.0

- package-lock.json
- package.json
- src/Popup/DragHandle.js
- src/Popup/Hand.js
- src/Popup/PopupBase.js
- src/Popup/PopupInsert/PopupHeader/styled.js
- src/Popup/styled.js
Resolves: #94 
⚠️ **Not running docs on this branch to avoid merge conflicts with #159**
> draggable popup!

- package-lock.json
- package.json
- src/Map/Map.js
> HOTFIX: add check for a map prop and do not create portal

- docs/PopupActionGroup.html
- docs/PopupActionItem.html
- docs/PopupDataList.html
- docs/PopupDefaultPage.html
- docs/PopupPageLayout.html
- docs/PopupPageLayoutChild.html
- docs/PopupTabs.html
Re-ran `npm run docs` on a separate branch to fix issues with docs
> New docs set

- app/Navbar.js
Fixes the SnackBar z-index so that the snackbar has precedence
> [FIX]: Snackbar z-index

- app/routes/demo/App.js
Quick fix for the demo site deploy
> [Fix] demo site import fix

- app/routes/space/App.js
- app/routes/space/ISS.js
- app/routes/space/README.md
- app/routes/space/SpaceX.js
Adding Docs for the space demo, please verify this info is accurate.
> [Docs] Add Docs to Space Demo

- README.md
- app/README.md
> Quick fix to the docs

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/Popup/utils.js
> fix Popup offset from margins added to map container

- package-lock.json
- package.json
> bump to 0.18.2

- config/jsdoc/template/bundler.js
> remove error in docs bundler

- config/jsdoc/template/bundler.js
> Open docs after they build locally

- app/package-lock.json
- app/package.json
- app/webpack.config.js
> fix broken demo site

- app/demos/world/App.js
> Finally Removing Diltz' crib from demo

- package-lock.json
- package.json
> Bump package-lock.json version number

- src/Draw/__snapshots__/DrawContainer.test.js.snap
> updated snapshots to fix broken tests

- package-lock.json
- package.json
- src/Popup/PopupInsert/PopupActionGroup/index.js
- src/Popup/PopupInsert/PopupActionGroup/styled.js
> fix bugs with flyout menu in popup

- src/Map/example.md
- src/Map/utils.js
- src/Popup/utils.js
- src/Popup/utils.test.js
- src/classes/VectorLayer.js
> Fixed out-of-date links to pages in OpenLayers website.

- docs/Map.html
- docs/Map_utils.js.html
- docs/PopupActionGroup.html
- docs/PopupActionItem.html
- docs/PopupDataList.html
- docs/PopupDefaultPage.html
- docs/PopupPageLayout.html
- docs/PopupPageLayoutChild.html
- docs/PopupTabs.html
- docs/Popup_utils.js.html
- docs/VectorLayer.html
- docs/classes_VectorLayer.js.html
- docs/global.html
> docs update

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
> bump to 1.2.0

- .github/workflows/deploy-to-s3.yml
Updated s3 bucket for new account
> Change s3 bucket

- docs/PopupActionGroup.html
- docs/PopupActionItem.html
- docs/PopupDataList.html
- docs/PopupDefaultPage.html
- docs/PopupPageLayout.html
- docs/PopupPageLayoutChild.html
- docs/PopupTabs.html
- docs/index.html
- src-docs/overrides/index.html
Updates the Bayer careers link
> updated req links

- package-lock.json
- package.json
- src/Controls/ZoomIn.js
- src/Controls/ZoomOut.js
- src/Draw/DrawContainer.js
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/Draw/utils.js
- src/Map/Map.js
- src/Map/utils.js
- src/__snapshots__/index.test.js.snap
> Fixed zoombox and zoom buttons from zooming in continuously

- package-lock.json
- package.json
- src/Draw/Draw.js
- src/Draw/DrawContainer.js
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/classes/VectorLayer.js
- src/classes/VectorLayer.test.js
> Make draw use internal vector layer implementation

- app/demos/world/App.js
- app/index.html
- src/LayerPanel/LayerPanel.js
- src/LayerPanel/LayerPanelLayersPage/index.js
- src/LayerPanel/LayerPanelList/index.js
- src/Map/Map.js
- src/Map/utils.js
> Add Hover Functionality 

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/LayerPanel/LayerPanelActionRemove/index.js
- src/LayerPanel/LayerPanelLayersPage/index.js
> Updates from supportv0 that need to be moved to 1.0

- docs/LayerPanel.html
- docs/LayerPanelActionRemove.html
- docs/LayerPanelLayersPage.html
- docs/LayerPanelList.html
- docs/LayerPanel_LayerPanel.js.html
- docs/LayerPanel_LayerPanelActionRemove_index.js.html
- docs/LayerPanel_LayerPanelLayersPage_index.js.html
- docs/LayerPanel_LayerPanelList_index.js.html
- docs/Map_Map.js.html
- docs/Map_utils.js.html
- docs/PopupActionGroup.html
- docs/PopupActionItem.html
- docs/PopupDataList.html
- docs/PopupDefaultPage.html
- docs/PopupPageLayout.html
- docs/PopupPageLayoutChild.html
- docs/PopupTabs.html
> had to run the docs

- src/LayerPanel/LayerPanelList/index.js
> layerpanel bottom drag doesnt work

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/LayerPanel/LayerPanelLayersPage/index.js
> Fix visibility issue

- data-sources/README.md
- data-sources/dataSources.json
Resolves: https://github.com/MonsantoCo/ol-kit/issues/80
Basically, I have a json file with a bunch of data sources, and a brief readme on what their contents are. Haven't added to docs site or anything, just starting the list.
> First pass at compiling list of open data sets

- package-lock.json
- package.json
- src/LayerPanel/LayerPanelLayersPage/index.js
> Layerpanel layer checkbox visibility bug

- src-docs/overrides/index.html
- Added Google Analytics to the ol-kit Landing Page
> Adding Google Analytics

- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/LayerPanel/LayerPanelLayersPage/index.js
- src/Map/utils.js
> add defaultProps context

- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/LayerPanel/LayerPanelLayersPage/index.js
- src/LayerPanel/LayerPanelList/index.js
> layer filter in layerpanellayerspage

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
> bump to 0.19.6

- src/Popup/PopupBase.js
- src/Popup/PopupInsert/PopupDataList/styled.js
- src/Popup/PopupInsert/PopupDefaultInsert.js
- src/Popup/PopupInsert/PopupDefaultPage/index.js
- src/Popup/PopupInsert/PopupHeader/styled.js
- src/Popup/styled.js
> updated popup card design

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/Popup/styled.js
> handle numbers and strings passed in as css width/height

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/Popup/styled.js
> Handle strings and numbers for height/width

- .github/workflows/deploy-branch-to-s3.yml
- devops/ol-kit-s3-router-cloudfront.js
All non-master branches will be accessible by going to demo.ol-kit.com/branch/$branchName
At some point we will need to add slack alerts to our internal slack
> Branch deploys

- package-lock.json
- package.json
- src-docs/tutorials/LayerPanel.md
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/LayerPanel/LayerPanelLayersPage/index.js
- src/LayerPanel/example.md
Some implementing apps are not building correctly because of the lack of `?.` on this line
> Optional Chaining Patch

- src/Draw/DrawContainer.js
- src/__snapshots__/index.test.js.snap
- src/classes/Preferences.js
- src/classes/index.js
> Preferences to LocalStorage

- app/demos/world/App.js
- src/LayerPanel/LayerPanelActionImport/utils.js
- src/LayerPanel/LayerPanelLayersPage/index.js
> Support for multiple shapefiles in a single zip archive

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/LayerStyler/__snapshots__/LayerStyler.test.js.snap
- src/__snapshots__/index.test.js.snap
> Downgrade turf difference

- package-lock.json
- package.json
> downgrade difference

- package-lock.json
- package.json
> remove ol dependency and move to devDependencies

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/LayerPanel/LayerPanelBase/styled.js
- src/LayerPanel/LayerPanelLayersPage/index.js
- src/LayerPanel/LayerPanelList/index.js
- src/LayerStyler/__snapshots__/LayerStyler.test.js.snap
- src/__snapshots__/index.test.js.snap
> Layerpanel render loop

- app/demos/world/App.js
- package-lock.json
- src/Map/utils.js
> Ol6 select overlapping features

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/LayerPanel/LayerPanelLayersPage/index.js
> pass empty array instead of undefined for features from layer

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
- src/Map/Map.js
> fix bug where nothing returned from onMapInit promise was not handled

- CODEOWNERS
- MAINTAINERS.md
- README.md
- jsdoc.json
- package.json
Resolves: Updating maintainers list
> maintainers list update

- src/Controls/Controls.js
- src/Controls/styled.js
> added in-line styles to map controls

- package-lock.json
- package.json
- src/Draw/__snapshots__/DrawContainer.test.js.snap
> Changed scope to @monsantoit

- README.md
> Readme update for ol-kit deprecation.
